    export class IndividualModel {
        mrnvp!: bigint
        mrn!: Number
        local_code!: bigint
        vehicle_number!: number
        person_number!: number
        first_name!: number
        middle_initial!: number
        last_name!: number
        prefix!: string
        street_address!: string
        city!: string
        state!: string
        zip_code!: string
        person_type!: string
        birth_date!: Date
        age!: number
        gender!: string
        position_in_vehicle!: string
        ejection_trapped!: string
        safety_equipment_used!: string
        safety_equipment_effective!: string
        injury_status!: string
        nature_of_injury!: string
        location_of_injury!: string
        test_given!: string
        test_results!: string
        drugs!: string
        ems_number!: string
        id!: number
        createdAt!: string
        updatedAt!: string
}